require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BusinessCategoryTemplatesController do

  # This should return the minimal set of attributes required to create a valid
  # BusinessCategoryTemplate. As you add validations to BusinessCategoryTemplate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "category" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BusinessCategoryTemplatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all business_category_templates as @business_category_templates" do
      business_category_template = BusinessCategoryTemplate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:business_category_templates).should eq([business_category_template])
    end
  end

  describe "GET show" do
    it "assigns the requested business_category_template as @business_category_template" do
      business_category_template = BusinessCategoryTemplate.create! valid_attributes
      get :show, {:id => business_category_template.to_param}, valid_session
      assigns(:business_category_template).should eq(business_category_template)
    end
  end

  describe "GET new" do
    it "assigns a new business_category_template as @business_category_template" do
      get :new, {}, valid_session
      assigns(:business_category_template).should be_a_new(BusinessCategoryTemplate)
    end
  end

  describe "GET edit" do
    it "assigns the requested business_category_template as @business_category_template" do
      business_category_template = BusinessCategoryTemplate.create! valid_attributes
      get :edit, {:id => business_category_template.to_param}, valid_session
      assigns(:business_category_template).should eq(business_category_template)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BusinessCategoryTemplate" do
        expect {
          post :create, {:business_category_template => valid_attributes}, valid_session
        }.to change(BusinessCategoryTemplate, :count).by(1)
      end

      it "assigns a newly created business_category_template as @business_category_template" do
        post :create, {:business_category_template => valid_attributes}, valid_session
        assigns(:business_category_template).should be_a(BusinessCategoryTemplate)
        assigns(:business_category_template).should be_persisted
      end

      it "redirects to the created business_category_template" do
        post :create, {:business_category_template => valid_attributes}, valid_session
        response.should redirect_to(BusinessCategoryTemplate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved business_category_template as @business_category_template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BusinessCategoryTemplate.any_instance.stub(:save).and_return(false)
        post :create, {:business_category_template => { "category" => "invalid value" }}, valid_session
        assigns(:business_category_template).should be_a_new(BusinessCategoryTemplate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BusinessCategoryTemplate.any_instance.stub(:save).and_return(false)
        post :create, {:business_category_template => { "category" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested business_category_template" do
        business_category_template = BusinessCategoryTemplate.create! valid_attributes
        # Assuming there are no other business_category_templates in the database, this
        # specifies that the BusinessCategoryTemplate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BusinessCategoryTemplate.any_instance.should_receive(:update_attributes).with({ "category" => "MyString" })
        put :update, {:id => business_category_template.to_param, :business_category_template => { "category" => "MyString" }}, valid_session
      end

      it "assigns the requested business_category_template as @business_category_template" do
        business_category_template = BusinessCategoryTemplate.create! valid_attributes
        put :update, {:id => business_category_template.to_param, :business_category_template => valid_attributes}, valid_session
        assigns(:business_category_template).should eq(business_category_template)
      end

      it "redirects to the business_category_template" do
        business_category_template = BusinessCategoryTemplate.create! valid_attributes
        put :update, {:id => business_category_template.to_param, :business_category_template => valid_attributes}, valid_session
        response.should redirect_to(business_category_template)
      end
    end

    describe "with invalid params" do
      it "assigns the business_category_template as @business_category_template" do
        business_category_template = BusinessCategoryTemplate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BusinessCategoryTemplate.any_instance.stub(:save).and_return(false)
        put :update, {:id => business_category_template.to_param, :business_category_template => { "category" => "invalid value" }}, valid_session
        assigns(:business_category_template).should eq(business_category_template)
      end

      it "re-renders the 'edit' template" do
        business_category_template = BusinessCategoryTemplate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BusinessCategoryTemplate.any_instance.stub(:save).and_return(false)
        put :update, {:id => business_category_template.to_param, :business_category_template => { "category" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested business_category_template" do
      business_category_template = BusinessCategoryTemplate.create! valid_attributes
      expect {
        delete :destroy, {:id => business_category_template.to_param}, valid_session
      }.to change(BusinessCategoryTemplate, :count).by(-1)
    end

    it "redirects to the business_category_templates list" do
      business_category_template = BusinessCategoryTemplate.create! valid_attributes
      delete :destroy, {:id => business_category_template.to_param}, valid_session
      response.should redirect_to(business_category_templates_url)
    end
  end

end
